### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by amalbabyconfianz** [rentpost/forte-payments-php#1]
Could not find a version of package rentpost/forte-payments-php matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

php version: 7.1.30
Laravel version: 5.4

**Comment by oojacoboo** [comment]
Do you have an example with this flag in the `composer.json` context?  I understand the concept of it.  However, the docs don't really provide any examples, I've never made use of it, and I doubt it's even that reliable across many composer packages.  I'm happy to add it in though.

**Comment by jdubreville** [comment]
This is happening because no versions of the library have been released.  So composer by default only allows versioned code to be added to your project.  Two solutions: 1) Fork the code base and make a tagged version of the code.  You could then pull changes as they are needed and update your code and re-version it.  2) Change your composer settings to allow dev-master branches to be pulled in.  You do this by adding the following to  your composer file "minimum-stability" : "dev"

**Comment by oojacoboo** [comment]
Just pushed v1.0.0.  I'll version future updates.  Thanks.
